#!/usr/bin/bash

err_count=0

SCORE=$(echo 'To: null@localhost
From: monit@localhost

Empty
' | curl --max-time 10 -s --data-binary @- --unix-socket /var/lib/rspamd/rspamd.sock http://rspamd/scan | jq -rc .default.required_score | sed 's/\..*//' )
if [[ ${SCORE} -ne 9999 ]]; then
  echo "Rspamd settings check failed, score returned: ${SCORE}"
  err_count=$(( ${err_count} + 1))
else
  echo "Rspamd settings check succeeded, score returned: ${SCORE}"
fi

# A dirty hack until a PING PONG event is implemented to worker proxy
# We expect an empty response, not a timeout
if [ "$(curl -s --max-time 10 ${host_ip}:9900 2> /dev/null ; echo $?)" == "28" ]; then
  echo "Milter check failed"
  err_count=$(( ${err_count} + 1 ));
else
  echo "Milter check succeeded"
fi

exit $err_count
