"""Add sogo tables

Revision ID: 1270737d431e
Revises: cf1ffc14619b
Create Date: 2025-02-19 16:43:14.948366

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1270737d431e"
down_revision: Union[str, None] = "cf1ffc14619b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sogo_acl",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("c_folder_id", sa.Integer(), nullable=False),
        sa.Column("c_object", sa.String(length=255), nullable=False),
        sa.Column("c_uid", sa.String(length=255), nullable=False),
        sa.Column("c_role", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("sogo_acl_c_folder_id_key", "sogo_acl", ["c_folder_id"], unique=False)
    op.create_index("sogo_acl_c_uid_key", "sogo_acl", ["c_uid"], unique=False)
    op.create_table(
        "sogo_admin",
        sa.Column("c_key", sa.String(length=255), server_default="", nullable=False),
        sa.Column("c_content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("c_key"),
    )
    op.create_table(
        "sogo_alarms_folder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("c_path", sa.String(length=255), nullable=False),
        sa.Column("c_name", sa.String(length=255), nullable=False),
        sa.Column("c_uid", sa.String(length=255), nullable=False),
        sa.Column("c_recurrence_id", sa.Integer(), nullable=True),
        sa.Column("c_alarm_number", sa.Integer(), nullable=False),
        sa.Column("c_alarm_date", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sogo_cache_folder",
        sa.Column("c_uid", sa.String(length=255), nullable=False),
        sa.Column("c_path", sa.String(length=255), nullable=False),
        sa.Column("c_parent_path", sa.String(length=255), nullable=True),
        sa.Column("c_type", sa.Integer(), nullable=False),
        sa.Column("c_creationdate", sa.Integer(), nullable=False),
        sa.Column("c_lastmodified", sa.Integer(), nullable=False),
        sa.Column("c_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("c_deleted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("c_content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("c_uid", "c_path"),
    )
    op.create_table(
        "sogo_folder_info",
        sa.Column("c_folder_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("c_path", sa.String(length=255), nullable=False),
        sa.Column("c_path1", sa.String(length=255), nullable=False),
        sa.Column("c_path2", sa.String(length=255), nullable=True),
        sa.Column("c_path3", sa.String(length=255), nullable=True),
        sa.Column("c_path4", sa.String(length=255), nullable=True),
        sa.Column("c_foldername", sa.String(length=255), nullable=False),
        sa.Column("c_location", sa.String(length=2048), nullable=True),
        sa.Column("c_quick_location", sa.String(length=2048), nullable=True),
        sa.Column("c_acl_location", sa.String(length=2048), nullable=True),
        sa.Column("c_folder_type", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("c_folder_id"),
    )
    op.create_index("sogo_folder_info_c_path_key", "sogo_folder_info", ["c_path"], unique=True)
    op.create_table(
        "sogo_quick_appointment",
        sa.Column("c_folder_id", sa.Integer(), nullable=False),
        sa.Column("c_name", sa.String(length=255), nullable=False),
        sa.Column("c_uid", sa.String(length=255), nullable=False),
        sa.Column("c_startdate", sa.Integer(), nullable=True),
        sa.Column("c_enddate", sa.Integer(), nullable=True),
        sa.Column("c_cycleenddate", sa.Integer(), nullable=True),
        sa.Column("c_title", sa.String(length=1000), nullable=False),
        sa.Column("c_participants", sa.Text(), nullable=True),
        sa.Column("c_isallday", sa.Boolean(), nullable=True),
        sa.Column("c_iscycle", sa.Boolean(), nullable=True),
        sa.Column("c_cycleinfo", sa.Text(), nullable=True),
        sa.Column("c_classification", sa.Integer(), nullable=False),
        sa.Column("c_isopaque", sa.Boolean(), nullable=False),
        sa.Column("c_status", sa.Integer(), nullable=False),
        sa.Column("c_priority", sa.Integer(), nullable=True),
        sa.Column("c_location", sa.String(length=255), nullable=True),
        sa.Column("c_orgmail", sa.String(length=255), nullable=True),
        sa.Column("c_partmails", sa.Text(), nullable=True),
        sa.Column("c_partstates", sa.Text(), nullable=True),
        sa.Column("c_category", sa.String(length=255), nullable=True),
        sa.Column("c_sequence", sa.Integer(), nullable=True),
        sa.Column("c_component", sa.String(length=10), nullable=False),
        sa.Column("c_nextalarm", sa.Integer(), nullable=True),
        sa.Column("c_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("c_folder_id", "c_name"),
    )
    op.create_table(
        "sogo_quick_contact",
        sa.Column("c_folder_id", sa.Integer(), nullable=False),
        sa.Column("c_name", sa.String(length=255), nullable=False),
        sa.Column("c_givenname", sa.String(length=255), nullable=True),
        sa.Column("c_cn", sa.String(length=255), nullable=True),
        sa.Column("c_sn", sa.String(length=255), nullable=True),
        sa.Column("c_screenname", sa.String(length=255), nullable=True),
        sa.Column("c_l", sa.String(length=255), nullable=True),
        sa.Column("c_mail", sa.Text(), nullable=True),
        sa.Column("c_o", sa.String(length=255), nullable=True),
        sa.Column("c_ou", sa.String(length=255), nullable=True),
        sa.Column("c_telephonenumber", sa.String(length=255), nullable=True),
        sa.Column("c_categories", sa.String(length=255), nullable=True),
        sa.Column("c_component", sa.String(length=10), nullable=False),
        sa.Column("c_hascertificate", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("c_folder_id", "c_name"),
    )
    op.create_table(
        "sogo_sessions_folder",
        sa.Column("c_id", sa.String(length=255), nullable=False),
        sa.Column("c_value", sa.String(length=255), nullable=False),
        sa.Column("c_creationdate", sa.Integer(), nullable=False),
        sa.Column("c_lastseen", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("c_id"),
    )
    op.create_table(
        "sogo_store",
        sa.Column("c_folder_id", sa.Integer(), nullable=False),
        sa.Column("c_name", sa.String(length=255), server_default="", nullable=False),
        sa.Column("c_content", sa.Text(), nullable=False),
        sa.Column("c_creationdate", sa.Integer(), nullable=False),
        sa.Column("c_lastmodified", sa.Integer(), nullable=False),
        sa.Column("c_version", sa.Integer(), nullable=False),
        sa.Column("c_deleted", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("c_folder_id", "c_name"),
    )
    op.create_table(
        "sogo_user_profile",
        sa.Column("c_uid", sa.String(length=255), nullable=False),
        sa.Column("c_defaults", sa.Text(), nullable=True),
        sa.Column("c_settings", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("c_uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sogo_user_profile")
    op.drop_table("sogo_store")
    op.drop_table("sogo_sessions_folder")
    op.drop_table("sogo_quick_contact")
    op.drop_table("sogo_quick_appointment")
    op.drop_index("sogo_folder_info_c_path_key", table_name="sogo_folder_info")
    op.drop_table("sogo_folder_info")
    op.drop_table("sogo_cache_folder")
    op.drop_table("sogo_alarms_folder")
    op.drop_table("sogo_admin")
    op.drop_index("sogo_acl_c_uid_key", table_name="sogo_acl")
    op.drop_index("sogo_acl_c_folder_id_key", table_name="sogo_acl")
    op.drop_table("sogo_acl")
    # ### end Alembic commands ###
