"""sogo tables

Revision ID: 9fbec9137efe
Revises: 8d3df567c75c
Create Date: 2025-02-04 14:29:13.298672

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fbec9137efe"
down_revision: Union[str, None] = "8d3df567c75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "_sogo_static_view",
        sa.Column("c_uid", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("c_name", sa.String(length=255), nullable=False),
        sa.Column("c_password", sa.String(length=255), server_default="", nullable=False),
        sa.Column("c_cn", sa.String(length=255), nullable=True),
        sa.Column("c_l", sa.String(length=255), nullable=True),
        sa.Column("c_o", sa.String(length=255), nullable=True),
        sa.Column("c_ou", sa.String(length=255), nullable=True),
        sa.Column("c_telephonenumber", sa.String(length=255), nullable=True),
        sa.Column("mail", sa.String(length=255), nullable=False),
        sa.Column("aliases", sa.Text(), nullable=False),
        sa.Column("ad_aliases", sa.String(length=6144), server_default="", nullable=False),
        sa.Column("ext_acl", sa.String(length=6144), server_default="", nullable=False),
        sa.Column("kind", sa.String(length=100), server_default="", nullable=False),
        sa.Column("multiple_bookings", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("c_uid"),
    )
    op.create_index("_sogo_static_view_domain_key", "_sogo_static_view", ["domain"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("_sogo_static_view_domain_key", table_name="_sogo_static_view")
    op.drop_table("_sogo_static_view")
    # ### end Alembic commands ###
