"""Backend models

Revision ID: a465e415e03d
Revises:
Create Date: 2025-01-27 04:02:51.911476

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a465e415e03d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("goto", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("private_comment", sa.Text(), nullable=True),
        sa.Column("public_comment", sa.Text(), nullable=True),
        sa.Column("sogo_visible", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("alias_address_key", "alias", ["address"], unique=True)
    op.create_index("alias_domain_key", "alias", ["domain"], unique=False)
    op.create_table(
        "alias_domain",
        sa.Column("alias_domain", sa.String(length=255), nullable=False),
        sa.Column("target_domain", sa.String(length=255), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("alias_domain"),
    )
    op.create_index("alias_domain_active_key", "alias_domain", ["active"], unique=False)
    op.create_index("alias_domain_target_domain_key", "alias_domain", ["target_domain"], unique=False)
    op.create_table(
        "bcc_maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("local_dest", sa.String(length=255), nullable=False),
        sa.Column("bcc_dest", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("type", sa.Enum("sender", "rcpt"), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("bcc_maps_local_dest_key", "bcc_maps", ["local_dest"], unique=False)
    op.create_table(
        "domain",
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("aliases", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mailboxes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("defquota", sa.BigInteger(), server_default="3072", nullable=False),
        sa.Column("maxquota", sa.BigInteger(), server_default="102400", nullable=False),
        sa.Column("quota", sa.BigInteger(), server_default="102400", nullable=False),
        sa.Column("relayhost", sa.Integer(), server_default="0", nullable=False),
        sa.Column("backupmx", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("gal", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("relay_all_recipients", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("relay_unknown_only", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("domain"),
    )
    op.create_table(
        "mailbox",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("mailbox_path_prefix", sa.String(length=150), server_default="/var/vmail/", nullable=True),
        sa.Column("quota", sa.BigInteger(), server_default="102400", nullable=False),
        sa.Column("local_part", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("custom_attributes", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("kind", sa.String(length=100), server_default="", nullable=False),
        sa.Column("multiple_bookings", sa.Integer(), server_default="-1", nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index("mailbox_domain_key", "mailbox", ["domain"], unique=False)
    op.create_index("mailbox_domain_local_part_key", "mailbox", ["domain", "local_part"], unique=True)
    op.create_index("mailbox_kind_key", "mailbox", ["kind"], unique=False)
    op.create_table(
        "quota2",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("messages", sa.BigInteger(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "quota2replica",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("messages", sa.BigInteger(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "recipient_maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("old_dest", sa.String(length=255), nullable=False),
        sa.Column("new_dest", sa.String(length=255), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("recipient_maps_old_dest_key", "recipient_maps", ["old_dest"], unique=False)
    op.create_table(
        "relayhosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("relayhosts_hostname_key", "relayhosts", ["hostname"], unique=False)
    op.create_table(
        "sender_acl",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("logged_in_as", sa.String(length=255), nullable=False),
        sa.Column("send_as", sa.String(length=255), nullable=False),
        sa.Column("external", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spamalias",
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("goto", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("validity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_table(
        "tls_policy_override",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dest", sa.String(length=255), nullable=False),
        sa.Column(
            "policy",
            sa.Enum("none", "may", "encrypt", "dane", "dane-only", "fingerprint", "verify", "secure"),
            nullable=False,
        ),
        sa.Column("parameters", sa.String(length=255), server_default="", nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("tls_policy_override_dest_key", "tls_policy_override", ["dest"], unique=False)
    op.create_table(
        "transports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=False),
        sa.Column("nexthop", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), server_default="", nullable=False),
        sa.Column("password", sa.String(length=255), server_default="", nullable=False),
        sa.Column("is_mx_based", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("transports_destination_key", "transports", ["destination"], unique=False)
    op.create_index("transports_nexthop_key", "transports", ["nexthop"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("transports_nexthop_key", table_name="transports")
    op.drop_index("transports_destination_key", table_name="transports")
    op.drop_table("transports")
    op.drop_index("tls_policy_override_dest_key", table_name="tls_policy_override")
    op.drop_table("tls_policy_override")
    op.drop_table("spamalias")
    op.drop_table("sender_acl")
    op.drop_index("relayhosts_hostname_key", table_name="relayhosts")
    op.drop_table("relayhosts")
    op.drop_index("recipient_maps_old_dest_key", table_name="recipient_maps")
    op.drop_table("recipient_maps")
    op.drop_table("quota2replica")
    op.drop_table("quota2")
    op.drop_index("mailbox_kind_key", table_name="mailbox")
    op.drop_index("mailbox_domain_local_part_key", table_name="mailbox")
    op.drop_index("mailbox_domain_key", table_name="mailbox")
    op.drop_table("mailbox")
    op.drop_table("domain")
    op.drop_index("bcc_maps_local_dest_key", table_name="bcc_maps")
    op.drop_table("bcc_maps")
    op.drop_index("alias_domain_target_domain_key", table_name="alias_domain")
    op.drop_index("alias_domain_active_key", table_name="alias_domain")
    op.drop_table("alias_domain")
    op.drop_index("alias_domain_key", table_name="alias")
    op.drop_index("alias_address_key", table_name="alias")
    op.drop_table("alias")
    # ### end Alembic commands ###
