"""Add sieve filters table

Revision ID: f3adbeb27923
Revises: 4ad58e01b14b
Create Date: 2025-03-29 21:59:29.047068

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from taramail.views import (
    SieveAfterView,
    SieveBeforeView,
)

# revision identifiers, used by Alembic.
revision: str = 'f3adbeb27923'
down_revision: str | None = '4ad58e01b14b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sieve_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('script_desc', sa.String(length=255), nullable=False),
    sa.Column('script_name', sa.Enum('active', 'inactive'), nullable=False),
    sa.Column('script_data', sa.Text(), nullable=False),
    sa.Column('filter_type', sa.Enum('postfilter', 'prefilter'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['mailbox.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sieve_filters_script_desc_key', 'sieve_filters', ['script_desc'], unique=False)
    op.create_index('sieve_filters_username_key', 'sieve_filters', ['username'], unique=False)
    op.drop_constraint('user_acl_ibfk_1', 'user_acl', type_='foreignkey')
    op.create_foreign_key(None, 'user_acl', 'mailbox', ['username'], ['username'], ondelete='CASCADE')
    op.drop_constraint('user_attributes_ibfk_1', 'user_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'user_attributes', 'mailbox', ['username'], ['username'], ondelete='CASCADE')
    SieveBeforeView.create(op)
    SieveAfterView.create(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_attributes', type_='foreignkey')
    op.create_foreign_key('user_attributes_ibfk_1', 'user_attributes', 'mailbox', ['username'], ['username'])
    op.drop_constraint(None, 'user_acl', type_='foreignkey')
    op.create_foreign_key('user_acl_ibfk_1', 'user_acl', 'mailbox', ['username'], ['username'])
    op.drop_index('sieve_filters_username_key', table_name='sieve_filters')
    op.drop_index('sieve_filters_script_desc_key', table_name='sieve_filters')
    op.drop_table('sieve_filters')
    SieveAfterView.drop(op)
    SieveBeforeView.drop(op)
    # ### end Alembic commands ###
